### ISSUE TITLE
Could you add a VST2 plugin package please?

### ISSUE THREAD

**Issue by neildarlow** [flathub/net.sonobus.SonoBus#11]
While I appreciate the availability of the VST3 plugin package, support for that format is very weak. To cite two applications, which SonoBus could be used with as a plugin, namely Ardour6 and OBS Studio neither of which support VST3 (and don't have plans to support them any time soon) but they do both support the VST2 format.

**Comment by hfiguiere** [comment]
it can't legally be built.

**Comment by hfiguiere** [comment]
Ardour support VST3, no problem (but you have to use the Ardour available as flatpak)

**Comment by neildarlow** [comment]
Ah, apologies, I missed that Ardour introduced VST3 support at version 6.5. I had been following a forum thread requesting that support which had a negative tone. The developers must have found time to implement it after all.

Is the VST, VST2 and AAX plugin support provided by upstream limited to specific platforms? I saw that those formats were available for SonoBus plugins. Is it Linux which is the blocker?

**Comment by hfiguiere** [comment]
I will reiterate: we cannot LEGALLY compile VST2 support. If you think it's unfair, you can direct your complaints to Steinberg, the gatekeeper of the VST standard.

**Comment by neildarlow** [comment]
I wasn't seeking to complain, I was looking for clarification.

How can projects like the LSP-Plugins project create VST2 plugins for distribution while a flatpak packaging of SonoBus cannot include them?
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by hfiguiere** [comment]
They used a reverse engineered API (VeSTige I think), while SonoBus uses the JUCE framework that requires the VST_SDK, which cannot be obtained legally anymore, unless you have a license from around 2018, and that's Steinbergs doing.

**Comment by neildarlow** [comment]
I see. The choice of that framework, while convenient, isn't the best. Hopefully the SonoBus developer will change this some time in the future.

Thank you for this clarification.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
